name: 📱 Android CI

env:
  main_project_module: app

on:
  push:
    branches: [ main, work ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 1 1 * *' # minute hour day month monday

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: ubuntu-latest,
            }
          # - {
          #     os: macos-latest,
          #   }
          # - {
          #     os: windows-latest,
          #   }  

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Change wrapper permissions
        run: cd AndroidCanLang; chmod +x ./gradlew

      # # # Run Tests Build
      # # - name: Run gradle tests
      #   run: cd AndroidCanLang; ./gradlew test --warning-mode all

      # Run Build Project
      - name: Build gradle project
        run: cd AndroidCanLang; ./gradlew build --warning-mode all
