name: 🌕 CMake Build Matrix

on:
  push:
  schedule:
    - cron: '15 1 1 * *' # minute hour day month monday

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrixJson: ${{ steps.set-matrix.outputs.value }}
    strategy:
      matrix:
        config:
          - {
            win: {
              bin: "src/Release/",
              cmakeBuildConfig: "--config Release ",
              cmakeConfig: "-T v143,host=x64",
              prescript: "chcp 65001",
            },
            unix: {
              bin: "./src/",
              prescript: "export CXX=clang++",
              cmakeConfig: "",
              cmakeBuildConfig: ""
            },
          }
    steps:
      - name: make values
        id: set-matrix
        shell: bash
        run: |
          WinConf=$(cat <<-END
            ${{ toJSON(matrix.config.win) }}
          END)
          WinConf="${WinConf%\}*}";

          UnixConf=$(cat <<-END
            ${{ toJSON(matrix.config.unix) }}
          END)
          UnixConf="${UnixConf%\}*}";

          # https://cmake.org/cmake/help/v4.3/manual/cmake-generators.7.html
          # https://cmake.org/cmake/help/v3.16/generator/Visual%20Studio%2016%202019.html#platform-selection

          matrixJson=$(cat <<-END
          [
            $WinConf, os:"windows-latest", name: "Windows-latest" },
            $WinConf, os:"windows-2022", name: "Windows-2022" },
            $UnixConf, os: "ubuntu-latest", name: "ubuntu-latest"},
            $UnixConf, os: "macos-latest", name: "mac-latest"},
          ]
          END)

          echo "value=${matrixJson}"
          echo "value=${matrixJson//$'\n'/}" >> $GITHUB_OUTPUT

  mybuild:
    needs: set-matrix
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: ${{ fromJson(needs.set-matrix.outputs.matrixJson) }}
    steps:
      - uses: actions/checkout@v6
      - name: "Set current date as env variable"
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        id: version

      - name: cmake
        run: |
          mkdir build
          cd build/

          ${{ matrix.config.prescript }}

          cmake ${{ matrix.config.cmakeConfig }} .. 
          cmake --build . ${{ matrix.config.cmakeBuildConfig }}
      
      - name: run test
        shell: bash
        run: |
          cd build/

          echo ${{ matrix.config.bin }}
          # ls ${{ matrix.config.bin }}/tests
          # ${{ matrix.config.bin }}/tests/test_run
          for SCRIPT in ${{ matrix.config.bin }}/tests/*
          do
          if [ -f $SCRIPT -a -x $SCRIPT ]
          then
          $SCRIPT
          fi
          done

      - name: Copy artifact
        shell: bash
        run: |
          cd build;
          clang++ --version;
          mkdir -p deb/${{ matrix.config.name }};
          cp -r ${{ matrix.config.bin }}/tests/* deb/${{ matrix.config.name }}
          ls -al deb/${{ matrix.config.name }}


      - uses: actions/upload-artifact@v6
        with:
          name: cshort_${{ matrix.config.name }}_${{ steps.version.outputs.builddate }}
          path: build/deb