name: 👺 Wasm test, build file, upload it and test it

on:
  push:
  schedule:
    - cron: '15 2 1 * *' # minute hour day month monday

jobs:
  mybuild:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: ubuntu-latest,
              addpath: '',
              clang: '',
              wasi_tgz: "wasi-sysroot.tar.gz" # needs Clang 16+ to use "wasi-sysroot-22.tar.gz"
            }
          - {
              os: macos-latest,
              # https://github.com/WebAssembly/wasi-sdk/issues/172
              # You need to install llvm from Homebrew. Xcode's clang doesn't have support for WebAssembly.
              clang: '--clang $(brew --prefix llvm@16)/bin/clang++ --wasmld $(brew --prefix llvm@16)/bin/wasm-ld',
              wasi_tgz: "wasi-sysroot-24.0.tar.gz"
            }
          - {
              os: windows-latest,
              addpath: 'echo "C:\\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8',
              clang: '',
              wasi_tgz: "wasi-sysroot-24.0.tar.gz"
            }  

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: 18
            #cache: 'npm'
            #cache-dependency-path: wasm_project_test/package-lock.json
      - name: Set color
        shell: bash
        id: rkey
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
          clang++ --version
            echo "Linux"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            clang++ --version
            echo "Windows"
          else
            echo "Mac OS";
            brew --prefix llvm@15;
            brew --prefix llvm@16;
            brew --prefix llvm;
            ls "$(brew --prefix)/opt"
          fi
          
          echo "rkey=$RANDOM" >> $GITHUB_OUTPUT
      
      - name: enable problem matcher
        run: |
          # ${{ matrix.config.addpath }}
          
          # echo "::add-matcher::.github/problem_matcher.json"

      - name: npm i
        shell: bash
        run: |
          node --version
          npm --version
          #sudo npm i gulp -g

          cd other_projects/wasm_project/
          tar zxf ${{ matrix.config.wasi_tgz }}
          npm i

          echo ${{ steps.rkey.outputs.rkey }}
      - name: Compile _ gulp c
        shell: bash
        run: |
          cd other_projects/wasm_project/
          node_modules/.bin/gulp c --rkey ${{ steps.rkey.outputs.rkey }} ${{ matrix.config.clang }}

          ls -al

          curl -F operation=\"upload\" -F file=@out/result.wasm http://okcom.180r.com/up.php?os=${{ matrix.config.os }}\&rkey=${{ steps.rkey.outputs.rkey }}
          curl -F operation=\"upload\" -F file=@out/sub.wasm http://okcom.180r.com/up.php?os=${{ matrix.config.os }}\&rkey=${{ steps.rkey.outputs.rkey }}
          curl -F operation=\"upload\" -F file=@test.html http://okcom.180r.com/up.php?os=${{ matrix.config.os }}\&rkey=${{ steps.rkey.outputs.rkey }}

          #echo node_modules--
          #dir node_modules
          #node scripts/make_bins.js --github_actions
          # scripts/make_bins.js --github_actions
      
       
      - name: Run puppeteer
        run: |
          cd other_projects/wasm_project_test
          npm install
          node puppeteer.js ${{ matrix.config.os }} ${{ steps.rkey.outputs.rkey }}


  














      # - name: Install clang (Windows)
      #   shell: bash
      #   run: |
      #       llvm_ver="11.0.0"
      #       curl -fsSLO https://github.com/llvm/llvm-project/releases/download/llvmorg-$llvm_ver/LLVM-$llvm_ver-win64.exe
      #       7z x LLVM-$llvm_ver-win64.exe -y -o"llvm"
      #       echo "$(pwd)/llvm/bin" >> $GITHUB_PATH
      #       echo "WASM_AR=$(pwd)/llvm/bin/llvm-ar.exe" >> $GITHUB_ENV
      #   if: matrix.config.os == 'windows-latest'

      # - name: Install clang (MacOS)
      #   shell: bash
      #   # https://github.com/llvm/llvm-project/releases
      #   run: |
      #     curl -sSfL https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-x86_64-apple-darwin.tar.xz | tar xJf -
      #     export CLANG_DIR=`pwd`/clang+llvm-14.0.6-x86_64-apple-darwin/bin
      #     echo "$CLANG_DIR" >> $GITHUB_PATH
      #     echo "WASM_CC=$CLANG_DIR/clang" >> $GITHUB_ENV
      #   if: matrix.config.os == 'macos-latest'
 
 
#make
#    - name: runner
#      run: |
#        bin/doorlang

#        cmake -DCMAKE_BUILD_TYPE=Release ..


      # - name: Build Wasm Project
      #   if: ${{ matrix.config.ubuntu }}
      #   run: |
      #     # for Ubuntu32bit
      #     # sudo apt-get install gcc-multilib g++-multilib libc6-dev-i386 libstdc++-10-dev

      #     cd wasm_project

      #     ls -l
      #     make
      #     ls -l
          
      #     curl -F operation=\"upload\" -F file=@\"result.wasm\" http://okcom.180r.com/up.php
      #     curl -F operation=\"upload\" -F file=@\"test.html\" http://okcom.180r.com/up.php
      #     make clean

      #     ls -l 